### ISSUE TITLE
Closes after one game

### ISSUE THREAD

**Issue by Ash7783** [MrFums/Valbot#34]
I left it running over night and when I woke up it was closed and only one game was played

**Comment by Ash7783** [comment]
I ran it again but this time I stuck around for it and it ended up with the same problem as another person. It detects the play again button, detects not in queue then cannot locate skip button repeats that until i move it back to menu.

**Comment by MrFums** [comment]
I dont have time to push a fix currently, but if you know basic python, if you head to the function that scans if you are at the XP screen (believe it is literally just called `xpscreen(self)`, you can then go change the `if x is not or x2 is not` part to call for the `play button function` (forgot its name) rather than checking for a skip button. This would essentially make it so it would always click the play button and restart the script as if you were starting it for the first time every iteration.
