### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MrCmailik** [MrFums/Valbot#35]
Hello!
I cant run valbot - here's short video. It's not possible to read the traceback,so i runned script in VS,and I'll leave the traceback below
I tried both python 3.8.0 and 3.9.0,both were added to system PATH,i tried it while Valorant was running and not
**Winver** - 1903,build 18363.1198
**Video** - youtu.be/wapUZKsxcjg
**Traceback** - pastebin.com/YnsxCDY6
Do you have any ideas of what can i do?

**Comment by MrFums** [comment]
If I remember correctly, this error is because of an incorrect python version. As such, you must download 
![image](https://user-images.githubusercontent.com/57535680/101982606-208ac800-3c6d-11eb-8a6a-964ae43c880b.png) [download here](https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe). @WolfAnto please could you confirm?

**Comment by WolfAnto** [comment]
Yes, the problem comes from the Python version.
It is necessary to take the version for AMD64/EM64T/x64.
If this doesn't work, contact me on discord

**Comment by MrFums** [comment]
assuming fixed

**Comment by MrCmailik** [comment]
Here's the problem - both python 3.8.0 and 3.9.0 that I used were amd versions
I have amd python 3.9.0 installed right now
