### ISSUE TITLE
crashes after opening

### ISSUE THREAD

**Issue by disterisk** [MrFums/Valbot#45]
hey um i want to use the bot but when i open the installer or any of the python file it crashes immediately after showing a second of cmd. Please tell me how to fix

**Comment by MrFums** [comment]
If I remember correctly, this error is because of an incorrect python version. As such, you must download 
![image](https://user-images.githubusercontent.com/57535680/101982606-208ac800-3c6d-11eb-8a6a-964ae43c880b.png) [download here](https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe). @WolfAnto please could you confirm?
